### ISSUE TITLE
false alarm in timestamps check 

### ISSUE THREAD

**Issue by gtarnin** [google/blueprint#279]
I'm building aosp Android 9. and from time to time I got this error that stop my build without any specific scenario. after some hours it can run without problems, even without any change in the code base.

out/soong/.bootstrap/blueprint-microfactory/test/test.passed -- out/soong/.bootstrap/blueprint-microfactory/test/test -test.short
--- FAIL: TestRebuildAfterRemoveOut (0.40s)
        microfactory_test.go:191: Output timestamp should be different, but both were 2020-01-19 16:43:14 +0200 IST
--- FAIL: TestRebuildAfterPartialBuild (0.43s)
        microfactory_test.go:191: Output timestamp should be different, but both were 2020-01-19 16:43:14 +0200 IST
--- FAIL: TestRebuildAfterMainChange (0.45s)
        microfactory_test.go:191: Output timestamp should be different, but both were 2020-01-19 16:43:14 +0200 IST
--- FAIL: TestRebuildAfterGoChange (0.58s)
        microfactory_test.go:191: Output timestamp should be different, but both were 2020-01-19 16:43:14 +0200 IST
FAIL
[  0% 170/93074] //external/aac:libFraunhoferAAC clang++ libFDK/src/FDK_tools_rom.cpp
ninja: build stopped: subcommand failed.
16:43:15 ninja failed with: exit status 1

**Comment by colincross** [comment]
What filesystem are you using for out/?

**Comment by danw** [comment]
And are you using Linux or Mac? If Linux, what does `stat out/Android.mk` return?

**Comment by gtarnin** [comment]
I'm building Ubuntu 18.04 running on VM Servers.

last time it happens, I add a sleep of 0.5 sec to the microfactory_test.go before the time check, and it "solve" the problem... 

about the stat out/Android.mk - I'll check that when it will happen again.

**Comment by gtarnin** [comment]
$ stat out/Android.mk
  File: out/Android.mk
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 801h/2049d      Inode: 52249215    Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/  ubuntu)   Gid: ( 1000/  ubuntu)
Access: 2020-01-20 15:54:03.000000000 +0200
Modify: 2020-01-20 15:54:03.000000000 +0200
Change: 2020-01-20 15:54:03.000000000 +0200
Birth: -

**Comment by lberki** [comment]
Closing this since we won't be resolving this after the archival of the project.
