### ISSUE TITLE
No Documentation

### ISSUE THREAD

**Issue by circutrider21** [google/blueprint#348]
I have looked everywhere and have not found any documentation on this build system. Is there even documentation to begin with.

**Comment by fuheihei** [comment]
I have the same question with you.  https://github.com/google/blueprint/issues/347
They closed my issue. I have to research by myself.

**Comment by circutrider21** [comment]
Well, What did you find?

**Comment by fuheihei** [comment]
Hope the documentation can help you
 https://note.qidong.name/demo/soong_build/

**Comment by fuheihei** [comment]
You can change attributes like "manifest","src" in Android.bp

**Comment by circutrider21** [comment]
Thanks!

**Comment by circutrider21** [comment]
I was looking for a fast build system that uses ninja

**Comment by circutrider21** [comment]
I thought this was the solution

But instead, I found [GN](https://gn.googlesource.com/gn/)

Much better and comes with really nice documentation. You should check it out!

**Comment by fuheihei** [comment]
Thank you, your documentation is very exact and helpful

**Comment by lberki** [comment]
Closing this since we won't be writing documentation after the archival of the project.
